persona_attributes:

  - name: "나이"
    description: "페르소나의 나이 (예: 28)"
  - name: "성별"
    description: "페르소나의 성별 (예: 여성)"
  - name: "직업"
    description: "페르소나의 직업 (예: 직장인)"
  - name: "소득 수준"
    description: "페르소나의 월 소득 수준 (예: 300만원)"
  - name: "거주 지역"
    description: "페르소나의 거주 지역 (예: 서울시 강남구)"
  - name: "가족 구성"
    description: "페르소나의 가족 구성 (예: 1인 가구)"
  - name: "성격"
    description: "페르소나의 성격 (예: 건강을 중시하는, 계획적인)"
  - name: "취미"
    description: "페르소나의 취미 (예: 운동, 요리)"
  - name: "미디어 소비 습관"
    description: "주로 이용하는 미디어 채널 (예: 인스타그램, 유튜브)"
  - name: "제품 선호도"
    description: "제품 선택 시 중요하게 생각하는 요소 (예: 맛, 영양성분, 가격)"
  - name: "건강 관심도"
    description: "건강에 대한 관심 수준 (1-10)"
  - name: "가격 민감도"
    description: "식품 물가 변화에 대한 민감도 (1-10, 10이 매우 민감)"
  - name: "마케팅 영향력"
    description: "광고 및 프로모션에 대한 영향력 (1-10, 10이 매우 영향 받음)"
  - name: "가정식 선호도"
    description: "집밥 및 홈쿡에 대한 선호도 (1-10, 10이 매우 선호)"
  - name: "계절성 구매 성향"
    description: "계절 및 트렌드(예: 컵빙수)에 따른 구매 성향 (1-10, 10이 매우 영향 받음)"
  - name: "선물 구매 성향"
    description: "명절 등 특별한 날 선물용 제품 구매 성향 (1-10, 10이 매우 선호)"
  - name: "평균 구매 수량"
    description: "제품 구매 시 평균적으로 구매하는 수량 (예: 1, 2, 3)"
  - name: "제품 적합도"
    description: "생성된 페르소나의 모든 특성(성격, 직업, 취미 등)을 바탕으로, 이 페르소나가 해당 제품을 구매할 확률을 1-10점 척도로 평가한 점수"
  - name: "구매 결정 핵심 이유"
    description: "페르소나가 위 '제품 적합도' 점수를 받은 가장 결정적인 이유에 대한 서술 (예: '건강을 중시하는 성격과 고단백 제품 특징이 잘 맞음')"
