products:
- product_name: 덴마크 하이그릭요거트 400g
  category:
    level_1: 우유류
    level_2: 발효유
    level_3: 호상-중대용량
  features:
  - 이중 유청분리 공범
  - 꾸덕한 질감
  - 고소함
  - 호상(떠먹는) 발효유
  - 고단백
  - 아연
  - 칼슘
  - 6-7월 TV
  - Youtube
  - SNS 광고 진행
  - 6-8월 수도권 중심 아파트 엘리베이터 광고
  - '광고모델: 일반인'
- product_name: 동원맛참 고소참기름 135g
  category:
    level_1: 참치
    level_2: 참치캔
    level_3: 라이트스탠다드참치
  features:
  - '광고모델: 안유진'
  - 참기름
  - 단백질
  - 셀레늄
  - 고소
- product_name: 동원맛참 고소참기름 90g
  category:
    level_1: 참치
    level_2: 참치캔
    level_3: 라이트스탠다드참치
  features:
  - '광고모델: 안유진'
  - 참기름
  - 단백질
  - 셀레늄
  - 고소
- product_name: 동원맛참 매콤참기름 135g
  category:
    level_1: 참치
    level_2: 참치캔
    level_3: 라이트스탠다드참치
  features:
  - '광고모델: 안유진'
  - 참기름
  - 단백질
  - 셀레늄
  - 매콤
- product_name: 동원맛참 매콤참기름 90g
  category:
    level_1: 참치
    level_2: 참치캔
    level_3: 라이트스탠다드참치
  features:
  - '광고모델: 안유진'
  - 참기름
  - 단백질
  - 셀레늄
  - 매콤
- product_name: 동원참치액 순 500g
  category:
    level_1: 조미소스
    level_2: 조미료
    level_3: 액상조미료
  features:
  - 훈연참치추출물 80%
  - 참기엑기스
  - 참치명가
  - 직접 잡은 참치
  - 가쓰오엑기스
  - 표고버섯
  - 무
  - 감초
  - 마늘
- product_name: 동원참치액 순 900g
  category:
    level_1: 조미소스
    level_2: 조미료
    level_3: 액상조미료
  features:
  - 훈연참치추출물 80%
  - 참기엑기스
  - 참치명가
  - 직접 잡은 참치
  - 가쓰오엑기스
  - 표고버섯
  - 무
  - 감초
  - 마늘
- product_name: 동원참치액 진 500g
  category:
    level_1: 조미소스
    level_2: 조미료
    level_3: 액상조미료
  features:
  - 훈연참치추출물 80%
  - 참기엑기스
  - 참치명가
  - 직접 잡은 참치
  - 가쓰오엑기스
  - 표고버섯
  - 무
  - 감초
  - 마늘
- product_name: 동원참치액 진 900g
  category:
    level_1: 조미소스
    level_2: 조미료
    level_3: 액상조미료
  features:
  - 훈연참치추출물 80%
  - 참기엑기스
  - 참치명가
  - 직접 잡은 참치
  - 가쓰오엑기스
  - 표고버섯
  - 무
  - 감초
  - 마늘
- product_name: 리챔 오믈레햄 200g
  category:
    level_1: 축산캔
    level_2: 고급축산캔
    level_3: 가미축산캔
  features:
  - 오믈렛(Omelet)과 햄(Ham)의 합성어
  - 저나트륨
  - 내열성 케첩 소스
- product_name: 리챔 오믈레햄 340g
  category:
    level_1: 축산캔
    level_2: 고급축산캔
    level_3: 가미축산캔
  features:
  - 오믈렛(Omelet)과 햄(Ham)의 합성어
  - 저나트륨
  - 내열성 케첩 소스
- product_name: 소화가 잘되는 우유로 만든 바닐라라떼 250mL
  category:
    level_1: 우유류
    level_2: 커피
    level_3: 커피-CUP
  features:
  - 락토프리
  - 저온효소 처리 기술
  - 유당 ZERO
  - 저당 트렌드
  - 신선한 1등급 원유
  - SNS 바이럴 2-6월
  - 광고 X
- product_name: 소화가 잘되는 우유로 만든 카페라떼 250mL
  category:
    level_1: 우유류
    level_2: 커피
    level_3: 커피-CUP
  features:
  - 락토프리
  - 저온효소 처리 기술
  - 유당 ZERO
  - 저당 트렌드
  - 신선한 1등급 원유
  - SNS 바이럴 2-6월
  - 광고 X
- product_name: 프리미엄 동원참치액 500g
  category:
    level_1: 조미소스
    level_2: 조미료
    level_3: 액상조미료
  features:
  - 훈연참치추출물 85%
  - 참기엑기스
  - 참치명가
  - 직접 잡은 참치
  - 가쓰오엑기스
  - 표고버섯
  - 무
  - 감초
  - 마늘
- product_name: 프리미엄 동원참치액 900g
  category:
    level_1: 조미소스
    level_2: 조미료
    level_3: 액상조미료
  features:
  - 훈연참치추출물 85%
  - 참기엑기스
  - 참치명가
  - 직접 잡은 참치
  - 가쓰오엑기스
  - 표고버섯
  - 무
  - 감초
  - 마늘
